# Generated by Django 4.2.1 on 2024-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_survey_date', models.CharField(blank=True, max_length=10, null=True)),
                ('second_survey_date', models.CharField(blank=True, max_length=10, null=True)),
                ('send_followups', models.BooleanField(default=False)),
                ('follow_cycle', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
