# Generated by Django 4.2.1 on 2024-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type_name',
        ),
        migrations.AlterField(
            model_name='answer',
            name='yes_no_answer',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('MAYBE', 'MAYBE')], max_length=10, null=True),
        ),
    ]
