# Generated by Django 4.2.1 on 2024-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_question_order_question_parent_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='info_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.IntegerField(default=2),
        ),
    ]
