# Generated by Django 4.2.1 on 2024-10-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_question_info_required_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_at', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='info_at',
            field=models.ManyToManyField(blank=True, null=True, related_name='info_at_options', to='dashboard.infooption'),
        ),
    ]
