# Generated by Django 4.2.1 on 2024-10-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_infooption_question_follow_up_question_info_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='info_at',
            field=models.ManyToManyField(blank=True, related_name='info_at_options', to='dashboard.infooption'),
        ),
    ]
