# Generated by Django 4.2.1 on 2024-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_answer_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='load_order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
